# pull official base image
FROM python:3.11-slim-bookworm

# set working directory
WORKDIR /usr/src/app

# set environment variables
ENV PIP_ROOT_USER_ACTION=ignore
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# install system dependencies
RUN apt-get update \
  && apt-get -y install netcat-openbsd gcc postgresql \
  libglib2.0-0 libglib2.0-dev libopus0 libvpx7 \
  && apt-get clean

# install python dependencies
RUN pip install --upgrade pip
COPY ./requirements.dev.txt .
RUN pip install -r requirements.dev.txt

# add app
COPY . .
