"""empty message

Revision ID: f580b4f5b6b6
Revises: 92cb5c9d9c24
Create Date: 2026-02-14 15:00:15.798026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f580b4f5b6b6'
down_revision: Union[str, None] = '92cb5c9d9c24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent', sa.Column('teaching_mode', sqlmodel.sql.sqltypes.AutoString(), nullable=False,server_default='default'))
    op.add_column('voice_conversation', sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('voice_conversation', 'summary')
    op.drop_column('agent', 'teaching_mode')
    # ### end Alembic commands ###
