"""empty message

Revision ID: 7ccd74781dd9
Revises: 362a99925e67
Create Date: 2026-02-12 17:33:12.347821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7ccd74781dd9'
down_revision: Union[str, None] = '362a99925e67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('filename', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('r2_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('chunk_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_id'), 'document', ['id'], unique=False)
    op.create_index(op.f('ix_document_user_id'), 'document', ['user_id'], unique=False)
    op.create_table('voice_conversation',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('room_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('room_sid', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ai_enabled', sa.Boolean(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('total_duration_seconds', sa.Integer(), nullable=False),
    sa.Column('participant_count', sa.Integer(), nullable=False),
    sa.Column('config', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voice_conversation_id'), 'voice_conversation', ['id'], unique=False)
    op.create_index(op.f('ix_voice_conversation_room_name'), 'voice_conversation', ['room_name'], unique=True)
    op.create_index(op.f('ix_voice_conversation_user_id'), 'voice_conversation', ['user_id'], unique=False)
    op.create_table('voice_message',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('conversation_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('participant_identity', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('participant_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('message_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['voice_conversation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voice_message_conversation_id'), 'voice_message', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_voice_message_participant_identity'), 'voice_message', ['participant_identity'], unique=False)
    op.drop_index(op.f('ix_voice_messages_conversation_id'), table_name='voice_messages')
    op.drop_index(op.f('ix_voice_messages_participant_identity'), table_name='voice_messages')
    op.drop_table('voice_messages')
    op.drop_index(op.f('ix_voice_conversations_id'), table_name='voice_conversations')
    op.drop_index(op.f('ix_voice_conversations_room_name'), table_name='voice_conversations')
    op.drop_index(op.f('ix_voice_conversations_user_id'), table_name='voice_conversations')
    op.drop_table('voice_conversations')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('voice_conversations',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('room_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('room_sid', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('ai_enabled', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('ended_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('total_duration_seconds', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('participant_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('config', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('voice_conversations_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('voice_conversations_pkey'))
    )
    op.create_index(op.f('ix_voice_conversations_user_id'), 'voice_conversations', ['user_id'], unique=False)
    op.create_index(op.f('ix_voice_conversations_room_name'), 'voice_conversations', ['room_name'], unique=True)
    op.create_index(op.f('ix_voice_conversations_id'), 'voice_conversations', ['id'], unique=False)
    op.create_table('voice_messages',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('conversation_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('participant_identity', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('participant_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('message_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['voice_conversations.id'], name=op.f('voice_messages_conversation_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('voice_messages_pkey'))
    )
    op.create_index(op.f('ix_voice_messages_participant_identity'), 'voice_messages', ['participant_identity'], unique=False)
    op.create_index(op.f('ix_voice_messages_conversation_id'), 'voice_messages', ['conversation_id'], unique=False)
    op.drop_index(op.f('ix_voice_message_participant_identity'), table_name='voice_message')
    op.drop_index(op.f('ix_voice_message_conversation_id'), table_name='voice_message')
    op.drop_table('voice_message')
    op.drop_index(op.f('ix_voice_conversation_user_id'), table_name='voice_conversation')
    op.drop_index(op.f('ix_voice_conversation_room_name'), table_name='voice_conversation')
    op.drop_index(op.f('ix_voice_conversation_id'), table_name='voice_conversation')
    op.drop_table('voice_conversation')
    op.drop_index(op.f('ix_document_user_id'), table_name='document')
    op.drop_index(op.f('ix_document_id'), table_name='document')
    op.drop_table('document')
    # ### end Alembic commands ###
