"""empty message

Revision ID: 362a99925e67
Revises: 
Create Date: 2026-02-11 17:08:24.834495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '362a99925e67'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS citext;")
    op.create_table('user',
    sa.Column('username', postgresql.CITEXT(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('disabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('voice_conversations',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('room_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('room_sid', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ai_enabled', sa.Boolean(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('total_duration_seconds', sa.Integer(), nullable=False),
    sa.Column('participant_count', sa.Integer(), nullable=False),
    sa.Column('config', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voice_conversations_id'), 'voice_conversations', ['id'], unique=False)
    op.create_index(op.f('ix_voice_conversations_room_name'), 'voice_conversations', ['room_name'], unique=True)
    op.create_index(op.f('ix_voice_conversations_user_id'), 'voice_conversations', ['user_id'], unique=False)
    op.create_table('voice_messages',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('conversation_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('participant_identity', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('participant_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('message_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['voice_conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voice_messages_conversation_id'), 'voice_messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_voice_messages_participant_identity'), 'voice_messages', ['participant_identity'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_voice_messages_participant_identity'), table_name='voice_messages')
    op.drop_index(op.f('ix_voice_messages_conversation_id'), table_name='voice_messages')
    op.drop_table('voice_messages')
    op.drop_index(op.f('ix_voice_conversations_user_id'), table_name='voice_conversations')
    op.drop_index(op.f('ix_voice_conversations_room_name'), table_name='voice_conversations')
    op.drop_index(op.f('ix_voice_conversations_id'), table_name='voice_conversations')
    op.drop_table('voice_conversations')
    op.drop_table('user')
    # ### end Alembic commands ###
