"""empty message

Revision ID: 754445f8d22c
Revises: d52d4b066229
Create Date: 2026-02-13 21:33:43.181714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '754445f8d22c'
down_revision: Union[str, None] = 'd52d4b066229'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('agent_user_id_fkey'), 'agent', type_='foreignkey')
    op.create_foreign_key(None, 'agent', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('agent_document_document_id_fkey'), 'agent_document', type_='foreignkey')
    op.drop_constraint(op.f('agent_document_agent_id_fkey'), 'agent_document', type_='foreignkey')
    op.create_foreign_key(None, 'agent_document', 'agent', ['agent_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'agent_document', 'document', ['document_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('document_user_id_fkey'), 'document', type_='foreignkey')
    op.create_foreign_key(None, 'document', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('voice_conversation_user_id_fkey'), 'voice_conversation', type_='foreignkey')
    op.drop_constraint(op.f('voice_conversation_agent_id_fkey'), 'voice_conversation', type_='foreignkey')
    op.create_foreign_key(None, 'voice_conversation', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'voice_conversation', 'agent', ['agent_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(op.f('voice_message_conversation_id_fkey'), 'voice_message', type_='foreignkey')
    op.create_foreign_key(None, 'voice_message', 'voice_conversation', ['conversation_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'voice_message', type_='foreignkey')
    op.create_foreign_key(op.f('voice_message_conversation_id_fkey'), 'voice_message', 'voice_conversation', ['conversation_id'], ['id'])
    op.drop_constraint(None, 'voice_conversation', type_='foreignkey')
    op.drop_constraint(None, 'voice_conversation', type_='foreignkey')
    op.create_foreign_key(op.f('voice_conversation_agent_id_fkey'), 'voice_conversation', 'agent', ['agent_id'], ['id'])
    op.create_foreign_key(op.f('voice_conversation_user_id_fkey'), 'voice_conversation', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'document', type_='foreignkey')
    op.create_foreign_key(op.f('document_user_id_fkey'), 'document', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'agent_document', type_='foreignkey')
    op.drop_constraint(None, 'agent_document', type_='foreignkey')
    op.create_foreign_key(op.f('agent_document_agent_id_fkey'), 'agent_document', 'agent', ['agent_id'], ['id'])
    op.create_foreign_key(op.f('agent_document_document_id_fkey'), 'agent_document', 'document', ['document_id'], ['id'])
    op.drop_constraint(None, 'agent', type_='foreignkey')
    op.create_foreign_key(op.f('agent_user_id_fkey'), 'agent', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
