"""empty message

Revision ID: d52d4b066229
Revises: 7ccd74781dd9
Create Date: 2026-02-13 08:21:52.562066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd52d4b066229'
down_revision: Union[str, None] = '7ccd74781dd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('system_prompt', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_id'), 'agent', ['id'], unique=False)
    op.create_index(op.f('ix_agent_user_id'), 'agent', ['user_id'], unique=False)
    op.create_table('agent_document',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('agent_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('document_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agent.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_document_agent_id'), 'agent_document', ['agent_id'], unique=False)
    op.create_index(op.f('ix_agent_document_document_id'), 'agent_document', ['document_id'], unique=False)
    op.create_index(op.f('ix_agent_document_id'), 'agent_document', ['id'], unique=False)
    op.add_column('voice_conversation', sa.Column('agent_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_voice_conversation_agent_id'), 'voice_conversation', ['agent_id'], unique=False)
    op.create_foreign_key(None, 'voice_conversation', 'agent', ['agent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'voice_conversation', type_='foreignkey')
    op.drop_index(op.f('ix_voice_conversation_agent_id'), table_name='voice_conversation')
    op.drop_column('voice_conversation', 'agent_id')
    op.drop_index(op.f('ix_agent_document_id'), table_name='agent_document')
    op.drop_index(op.f('ix_agent_document_document_id'), table_name='agent_document')
    op.drop_index(op.f('ix_agent_document_agent_id'), table_name='agent_document')
    op.drop_table('agent_document')
    op.drop_index(op.f('ix_agent_user_id'), table_name='agent')
    op.drop_index(op.f('ix_agent_id'), table_name='agent')
    op.drop_table('agent')
    # ### end Alembic commands ###
